services:
  - mssql2017

install:
  - ps: Install-Product node ''
  - npm ci

build_script:
  - ps: .\appveyor\setup.ps1
  - npm run build
  - npm link
  - ssc pull -c ./appveyor/config.json

test_script:
  - npm run test:appveyor
